# Generated by Django 5.2.11 on 2026-02-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('ruc', 'RUC'), ('ce', 'Carné de Extranjería'), ('pasaporte', 'Pasaporte')], max_length=20)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
