# Generated by Django 5.2.11 on 2026-02-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, default='', max_length=200)),
                ('direccion', models.CharField(blank=True, default='', max_length=300)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('encargado', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'emisores',
                'db_table': 'emisor',
            },
        ),
    ]
