# Generated by Django 5.2.11 on 2026-02-13 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura')], max_length=20)),
                ('serie', models.CharField(max_length=10)),
                ('correlativo', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField()),
                ('gravada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=5)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('sunat_enviada', models.BooleanField(default=False)),
                ('sunat_aceptada', models.BooleanField(default=False)),
                ('codigo_respuesta', models.IntegerField(blank=True, null=True)),
                ('descripcion_respuesta', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='clientes.cliente')),
            ],
            options={
                'db_table': 'comprobantes',
                'ordering': ['-created_at'],
                'unique_together': {('serie', 'correlativo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(default='UNI', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250)),
                ('detalle_adicional', models.CharField(blank=True, default='', max_length=250)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comprobantes.comprobante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'db_table': 'detalle_comprobante',
            },
        ),
    ]
