# Generated by Django 5.2.11 on 2026-02-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('anulado', 'Anulado')], default='vigente', max_length=20),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
