# Generated by Django 5.2.7 on 2026-02-18 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estado')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Trabajador')),
                ('nombre_usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('contraseña', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='usuarios.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'trabajador',
                'ordering': ['nombre_usuario'],
            },
        ),
    ]
